# Generated by Django 5.2.1 on 2025-05-27 07:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Participacion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('tipo_participacion', models.CharField(choices=[('PREGUNTA', 'Pregunta'), ('RESPUESTA', 'Respuesta'), ('DEBATE', 'Debate'), ('EXPOSICION', 'Exposición'), ('EJERCICIO', 'Ejercicio en Pizarra'), ('TRABAJO_GRUPO', 'Trabajo en Grupo'), ('OTRO', 'Otro')], max_length=50)),
                ('calificacion', models.DecimalField(decimal_places=1, max_digits=3, validators=[django.core.validators.MinValueValidator(1.0), django.core.validators.MaxValueValidator(5.0)])),
                ('observacion', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Participación',
                'verbose_name_plural': 'Participaciones',
                'db_table': 'participacion',
            },
        ),
    ]
