# Generated by Django 5.2.1 on 2025-05-27 07:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        ('tutors', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('ci', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('fecha_nacimiento', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('usuario', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Estudiante',
                'verbose_name_plural': 'Estudiantes',
                'db_table': 'estudiante',
            },
        ),
        migrations.CreateModel(
            name='Inscripcion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_inscripcion', models.DateField()),
                ('fecha_baja', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('ACTIVO', 'Activo'), ('RETIRADO', 'Retirado'), ('TRASLADADO', 'Trasladado'), ('SUSPENDIDO', 'Suspendido')], default='ACTIVO', max_length=20)),
                ('motivo_baja', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ci_estudiante', models.ForeignKey(db_column='ci_estudiante', on_delete=django.db.models.deletion.CASCADE, to='students.estudiante')),
                ('codigo_curso', models.ForeignKey(db_column='codigo_curso', on_delete=django.db.models.deletion.CASCADE, to='courses.curso')),
            ],
            options={
                'verbose_name': 'Inscripción',
                'verbose_name_plural': 'Inscripciones',
                'db_table': 'inscripcion',
                'unique_together': {('ci_estudiante', 'codigo_curso', 'estado')},
            },
        ),
        migrations.CreateModel(
            name='TutorEstudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parentesco', models.CharField(choices=[('PADRE', 'Padre'), ('MADRE', 'Madre'), ('ABUELO', 'Abuelo'), ('ABUELA', 'Abuela'), ('TIO', 'Tío'), ('TIA', 'Tía'), ('HERMANO', 'Hermano'), ('HERMANA', 'Hermana'), ('TUTOR_LEGAL', 'Tutor Legal'), ('OTRO', 'Otro')], max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('ci_estudiante', models.ForeignKey(db_column='ci_estudiante', on_delete=django.db.models.deletion.CASCADE, to='students.estudiante')),
                ('ci_tutor', models.ForeignKey(db_column='ci_tutor', on_delete=django.db.models.deletion.CASCADE, to='tutors.tutor')),
            ],
            options={
                'verbose_name': 'Relación Tutor-Estudiante',
                'verbose_name_plural': 'Relaciones Tutor-Estudiante',
                'db_table': 'tutor_estudiante',
                'unique_together': {('ci_tutor', 'ci_estudiante')},
            },
        ),
    ]
