# Generated by Django 5.2.1 on 2025-05-27 06:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campo',
            fields=[
                ('codigo', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('valor', models.SmallIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Campo',
                'verbose_name_plural': 'Campos',
                'db_table': 'campo',
            },
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('codigo', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('nivel', models.CharField(max_length=50)),
                ('paralelo', models.CharField(max_length=1)),
                ('gestion', models.SmallIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Curso',
                'verbose_name_plural': 'Cursos',
                'db_table': 'curso',
            },
        ),
        migrations.CreateModel(
            name='Periodo',
            fields=[
                ('codigo', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Período',
                'verbose_name_plural': 'Períodos',
                'db_table': 'periodo',
            },
        ),
        migrations.CreateModel(
            name='Criterio',
            fields=[
                ('codigo', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('codigo_campo', models.ForeignKey(db_column='codigo_campo', on_delete=django.db.models.deletion.CASCADE, to='courses.campo')),
                ('codigo_periodo', models.ForeignKey(db_column='codigo_periodo', on_delete=django.db.models.deletion.CASCADE, to='courses.periodo')),
            ],
            options={
                'verbose_name': 'Criterio',
                'verbose_name_plural': 'Criterios',
                'db_table': 'criterio',
            },
        ),
    ]
