# Generated by Django 5.2.1 on 2025-06-04 02:35

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '__first__'),
        ('students', '__first__'),
        ('subjects', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActaNota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('EN_CURSO', 'En Curso'), ('APROBADO', 'Aprobado'), ('REPROBADO', 'Reprobado'), ('ABANDONADO', 'Abandonado')], default='EN_CURSO', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('ci_estudiante', models.ForeignKey(db_column='ci_estudiante', on_delete=django.db.models.deletion.CASCADE, to='students.estudiante')),
                ('codigo_curso', models.ForeignKey(db_column='codigo_curso', on_delete=django.db.models.deletion.CASCADE, to='courses.curso')),
                ('codigo_materia', models.ForeignKey(db_column='codigo_materia', on_delete=django.db.models.deletion.CASCADE, to='subjects.materia')),
            ],
            options={
                'verbose_name': 'Acta de Nota',
                'verbose_name_plural': 'Actas de Notas',
                'db_table': 'acta_nota',
                'unique_together': {('codigo_curso', 'codigo_materia', 'ci_estudiante')},
            },
        ),
        migrations.CreateModel(
            name='Nota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('ci_estudiante', models.ForeignKey(db_column='ci_estudiante', on_delete=django.db.models.deletion.CASCADE, to='students.estudiante')),
                ('codigo_curso', models.ForeignKey(db_column='codigo_curso', on_delete=django.db.models.deletion.CASCADE, to='courses.curso')),
                ('codigo_materia', models.ForeignKey(db_column='codigo_materia', on_delete=django.db.models.deletion.CASCADE, to='subjects.materia')),
                ('id_criterio', models.ForeignKey(db_column='id_criterio', on_delete=django.db.models.deletion.CASCADE, to='courses.criterio')),
            ],
            options={
                'verbose_name': 'Nota',
                'verbose_name_plural': 'Notas',
                'db_table': 'nota',
                'unique_together': {('codigo_curso', 'codigo_materia', 'ci_estudiante', 'id_criterio')},
            },
        ),
    ]
