# Generated by Django 5.2.1 on 2025-05-27 07:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        ('grades', '0001_initial'),
        ('students', '0001_initial'),
        ('subjects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='actanota',
            name='ci_estudiante',
            field=models.ForeignKey(db_column='ci_estudiante', on_delete=django.db.models.deletion.CASCADE, to='students.estudiante'),
        ),
        migrations.AddField(
            model_name='actanota',
            name='codigo_curso',
            field=models.ForeignKey(db_column='codigo_curso', on_delete=django.db.models.deletion.CASCADE, to='courses.curso'),
        ),
        migrations.AddField(
            model_name='actanota',
            name='codigo_materia',
            field=models.ForeignKey(db_column='codigo_materia', on_delete=django.db.models.deletion.CASCADE, to='subjects.materia'),
        ),
        migrations.AddField(
            model_name='nota',
            name='ci_estudiante',
            field=models.ForeignKey(db_column='ci_estudiante', on_delete=django.db.models.deletion.CASCADE, to='students.estudiante'),
        ),
        migrations.AddField(
            model_name='nota',
            name='codigo_criterio',
            field=models.ForeignKey(db_column='codigo_criterio', on_delete=django.db.models.deletion.CASCADE, to='courses.criterio'),
        ),
        migrations.AddField(
            model_name='nota',
            name='codigo_curso',
            field=models.ForeignKey(db_column='codigo_curso', on_delete=django.db.models.deletion.CASCADE, to='courses.curso'),
        ),
        migrations.AddField(
            model_name='nota',
            name='codigo_materia',
            field=models.ForeignKey(db_column='codigo_materia', on_delete=django.db.models.deletion.CASCADE, to='subjects.materia'),
        ),
        migrations.AlterUniqueTogether(
            name='actanota',
            unique_together={('codigo_curso', 'codigo_materia', 'ci_estudiante')},
        ),
        migrations.AlterUniqueTogether(
            name='nota',
            unique_together={('codigo_curso', 'codigo_materia', 'ci_estudiante', 'codigo_criterio')},
        ),
    ]
