# Generated by Django 5.2.1 on 2025-06-05 02:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '__first__'),
        ('students', '__first__'),
        ('subjects', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('estado', models.CharField(choices=[('presente', 'Presente'), ('ausente', 'Ausente'), ('tardanza', 'Tardanza'), ('justificado', 'Justificado')], default='ausente', max_length=12)),
                ('observacion', models.CharField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('ci_estudiante', models.ForeignKey(db_column='ci_estudiante', on_delete=django.db.models.deletion.CASCADE, to='students.estudiante')),
                ('codigo_curso', models.ForeignKey(db_column='codigo_curso', on_delete=django.db.models.deletion.CASCADE, to='courses.curso')),
                ('codigo_materia', models.ForeignKey(db_column='codigo_materia', on_delete=django.db.models.deletion.CASCADE, to='subjects.materia')),
            ],
            options={
                'verbose_name': 'Asistencia',
                'verbose_name_plural': 'Asistencias',
                'db_table': 'asistencia',
                'unique_together': {('codigo_curso', 'codigo_materia', 'ci_estudiante', 'fecha')},
            },
        ),
    ]
