# Generated by Django 5.2.1 on 2025-05-27 06:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        ('subjects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Docente',
            fields=[
                ('ci', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telefono', models.CharField(max_length=20)),
                ('fecha_ingreso', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('usuario', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Docente',
                'verbose_name_plural': 'Docentes',
                'db_table': 'docente',
            },
        ),
        migrations.CreateModel(
            name='AsignacionCurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('codigo_curso', models.ForeignKey(db_column='codigo_curso', on_delete=django.db.models.deletion.CASCADE, to='courses.curso')),
                ('codigo_materia', models.ForeignKey(db_column='codigo_materia', on_delete=django.db.models.deletion.CASCADE, to='subjects.materia')),
                ('ci_docente', models.ForeignKey(db_column='ci_docente', on_delete=django.db.models.deletion.CASCADE, to='teachers.docente')),
            ],
            options={
                'verbose_name': 'Asignación de Curso',
                'verbose_name_plural': 'Asignaciones de Curso',
                'db_table': 'asignacion_curso',
                'unique_together': {('codigo_curso', 'codigo_materia')},
            },
        ),
    ]
